const $=s=>document.querySelector(s);
const TYPES=[{id:'home',name:'움집',sprite:0,wood:10,food:32,max:6,stage:0,pop:0,desc:'일하는 주민 +2'},{id:'farm',name:'밭',sprite:1,wood:30,food:10,max:6,stage:0,pop:6,desc:'식량 수확 증가 · 주민 소폭 증가'},{id:'store',name:'공동 창고',sprite:2,wood:36,food:40,max:2,stage:3,pop:14,desc:'모든 운반량 +2'},{id:'square',name:'모임터',sprite:3,wood:32,food:38,max:2,stage:3,pop:14,desc:'홍익 +15 · 나눔'}];
const WEATHER=[{id:'drought',name:'메마른 대지',icon:'☀',skill:'rain',who:'우사',effect:'농사 수확량 50% 감소',text:'비가 오지 않아 작물이 시들고 있어요. 비를 맡은 우사에게 도움을 청해요.',class:'weather-drought'},{id:'rainstorm',name:'그치지 않는 폭우',icon:'☂',skill:'cloud',who:'운사',effect:'모든 주민 이동 속도 35% 감소',text:'먹구름이 몰려와 길이 젖었어요. 구름을 맡은 운사에게 구름을 걷어 달라고 해요.',class:'weather-rain'},{id:'gale',name:'거센 바람',icon:'≋',skill:'wind',who:'풍백',effect:'벌목 작업 시간 2배',text:'거센 바람에 숲이 흔들려요. 바람을 맡은 풍백에게 바람을 잠재워 달라고 해요.',class:'weather-wind'}];
const STAGES=[
{title:'신단수 아래 첫 마을',desc:'움집과 밭을 마련하고 주민들이 가져오는 첫 수확을 기다려요.',label:'환웅의 강림 · 신시',story:'인간 세상을 널리 이롭게 하고자 환웅이 무리 삼천을 거느리고 하늘에서 내려왔다. 신단수 아래 터를 잡으니, 이곳이 곧 신시라. 환웅은 이곳에서 사람들의 삶을 보살피기 시작하였다.',note:'신화의 이야기 · 주민 수와 건설은 게임을 위한 재구성이에요.',lessons:[0]},
{title:'비와 구름, 바람의 힘',desc:'세 조력자가 합류했어요. 밭을 넓히고 서로 다른 날씨 사건을 세 번 해결해요.',label:'풍백·우사·운사 · 사람들의 삶',story:'환웅에게는 날씨를 다스리는 세 명의 신이 있었다.\n우사는 비를, 운사는 구름을, 풍백은 바람을 맡았으니,\n세 신의 도움으로 마을에 농사가 잘 되었다.',note:'세 조력자는 신화에 등장해요. 개별 재해와 해결 능력은 게임용 창작이에요.',lessons:[1]},
{title:'동굴 속의 작은 약속',desc:'곰에게 쑥과 마늘 꾸러미를 보내요. 세 번의 돌봄을 마치면 웅녀의 이야기가 열려요.',label:'곰과 호랑이 · 웅녀',story:'그 무렵 곰과 호랑이가 사람이 되기를 청하니, 환웅이 쑥과 마늘을 내리며 백 일 동안 햇빛을 보지 말라 일렀다. 호랑이는 참지 못하고 떠났으나, 곰은 끝내 견디어 삼칠일 만에 여인의 몸을 얻으니 곧 웅녀더라.',note:'삼칠일은 21일이에요. 게임의 3회 돌봄과 대기 시간은 실제 신화의 시간과 달라요.',lessons:[2]},
{title:'널리 이로운 나라',desc:'함께 쓸 창고와 모임터를 만들고 식량을 나누어요. 단군의 나라를 세울 준비예요.',label:'웅녀와 환웅 · 단군왕검의 탄생',story:'환웅과 웅녀 사이에서 단군왕검이 태어나 자라 나라를 세웠다.\n여러 마을이 힘을 모아 큰 나라가 되었으니, 이를 고조선이라 하였다.',note:'기원전 2333년은 전통적으로 전해 오는 건국 연대이며, 확인된 정확한 날짜와 구분해요.',lessons:[3]},
{title:'하늘이 열린 날',desc:'마을의 마지막 잔치를 준비해요. 식량을 모으고 우리의 실천 약속을 남겨요.',label:'고조선의 건국 · 오늘의 개천절',story:'먼 옛날 나라가 열린 그날을 기려, 오늘 우리는 해마다 시월 삼일을 개천절이라 부른다. 널리 사람을 이롭게 하라던 그 뜻은 오늘의 작은 나눔 속에서도 이어지고 있느니라.',note:'개천절은 양력 10월 3일인 국경일이에요. 10월 9일 한글날과 구분해요.',lessons:[5]}
];
const POS=[[34.9,28.35],[27.5,37.45],[34.9,37.45],[22.075,47.75],[30.025,47.75],[22.075,56.85],[30.025,56.85],[70.55,54.55],[59.325,56.275],[43.975,64.225],[59.325,64.225],[34.05,63.1],[24.95,71.1],[34.05,71.1],[42,29],[56,31],[50,42],[38,46],[64,52],[30,63.5],[64,67],[66,60],[60.04,46.13],[29.73,71.9],[52.2,69.33],[39.02,59.11]];
let s,selected=null,toastTimer=0,quizQueue=[],quizIndex=0,quizDone=null,last=0,uiClock=0;
function fresh(){return {stage:0,time:0,food:18,wood:28,heart:20,lots:Array(26).fill(null),npcs:[],collected:0,solved:[],event:null,eventAt:18,eventIndex:0,cooldown:{rain:0,cloud:0,wind:0},care:0,careTime:0,shares:0,shareCooldown:0,learned:[],paused:false,speed:1,finished:false,communityAt:105,reflection:''}}
function count(id,includeConstruction=false){return s.lots.filter(l=>l&&l.id===id&&(includeConstruction||l.remaining<=0)).length}
function population(){return 4+count('home')*2+count('farm')*(1+s.stage)}
function notify(t){$('#toast').textContent=t;$('#toast').classList.remove('quiet');toastTimer=7}
function show(html){$('#modalBody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function close(){ $('#modal').close();quizQueue=[];quizDone=null }
function floatText(x,y,text){const n=document.createElement('span');n.className='float';n.style.left=x+'%';n.style.top=y+'%';n.textContent=text;$('#particles').append(n);setTimeout(()=>n.remove(),1800)}
const WOOD_SPOTS=[[16,35],[21,32],[27,36],[13,44],[19,47],[25,45],[14,53],[21,54],[28,51]];
const FARM_OFFSETS=[[2,3],[-3,2],[3,-2],[-2,-3],[4,1],[-4,1],[1,4],[-1,-4],[3,3]];
function targetFor(n){if(n.job==='wood'){const p=WOOD_SPOTS[n.id%WOOD_SPOTS.length];return {x:p[0],y:p[1]}}const farms=s.lots.map((l,i)=>l?.id==='farm'&&l.remaining<=0?i:-1).filter(i=>i>=0);if(farms.length){let p=POS[farms[n.id%farms.length]];const o=FARM_OFFSETS[n.id%FARM_OFFSETS.length];return {x:p[0]+o[0],y:p[1]+o[1]}}return {x:60+(n.id%5)*4,y:58+(n.id%3)*4}}
function spawnPeople(){while(s.npcs.length<population()){let id=s.npcs.length;s.npcs.push({id,job:id%2?'wood':'food',x:45+id*.6,y:53+id*.35,mode:'going',work:0,cargo:0});const n=document.createElement('div');n.id='npc'+id;n.className='npc';n.innerHTML=`<div class="art sprite-${id%2?5:4}"></div><span class="cargo"></span><span class="job"></span>`;$('#people').append(n)}}
const RETURN_SPOTS_WOOD=[[32,50],[37,54],[41,51],[35,57],[39,48]];
const RETURN_SPOTS_FOOD=[[54,52],[58,56],[62,53],[56,58],[60,50]];
function updateNPC(n,dt){const workAt=targetFor(n);const rp=(n.job==='wood'?RETURN_SPOTS_WOOD:RETURN_SPOTS_FOOD)[n.id%5];const target=n.mode==='returning'?{x:rp[0],y:rp[1]}:workAt;let dx=target.x-n.x,dy=target.y-n.y,dist=Math.hypot(dx,dy);if(n.mode!=='working'){n.stepClock=(n.stepClock||0)+dt;const stepInterval=.13;let moved=false;if(n.stepClock>=stepInterval){const ticks=Math.floor(n.stepClock/stepInterval);n.stepClock-=ticks*stepInterval;let step=stepInterval*ticks*4.7*(s.event?.id==='rainstorm'?.65:1);if(dist<=step){n.x=target.x;n.y=target.y;if(n.mode==='going'){n.mode='working';n.work=0}else{s[n.job]+=n.cargo;if(n.job==='food')s.collected+=n.cargo;floatText(n.x,n.y,(n.job==='food'?'🌾':'목재')+' +'+n.cargo);n.cargo=0;n.mode='going'}}else{n.x+=dx/dist*step;n.y+=dy/dist*step}moved=true}n.stepped=moved}else{n.stepped=false;n.work+=dt;let duration=n.job==='wood'?(s.event?.id==='gale'?10:5.5):7;if(n.work>=duration){let amount=n.job==='wood'?3:2+Math.min(count('farm'),3)*1.3;amount+=count('store')*1.2;if(n.job==='food'&&s.event?.id==='drought')amount=Math.max(1,Math.floor(amount/2));n.cargo=Math.max(1,Math.round(amount));n.mode='returning'}}const el=$('#npc'+n.id);if(el){el.style.left=n.x+'%';el.style.top=n.y+'%';el.className='npc '+(n.mode==='working'?'working':'walking')+(n.stepped?' step':'');el.querySelector('.cargo').textContent=n.cargo?(n.job==='food'?'🌾':'목재'):'';el.querySelector('.job').textContent=n.mode==='working'?(n.job==='food'?'收 수확 중'.replace('收 ',''):'벌목 중'):n.mode==='returning'?'운반 중':''}}
function objectives(){switch(s.stage){case 0:return [{text:'움집 완성',now:count('home'),goal:1},{text:'밭 완성',now:count('farm'),goal:1},{text:'주민들이 식량 수확하기',now:s.collected,goal:20}];case 1:return [{text:'밭 2곳으로 넓히기',now:count('farm'),goal:2},{text:'우사·운사·풍백으로 재해 해결',now:s.solved.length,goal:3}];case 2:return [{text:'쑥과 마늘 꾸러미 보내기',now:s.care,goal:3},{text:'곰의 기다림 함께하기',now:s.care>=3&&s.careTime<=0?1:0,goal:1}];case 3:return [{text:'공동 창고 완성',now:count('store'),goal:1},{text:'모임터 완성',now:count('square'),goal:1},{text:'이웃에게 식량 나누기',now:s.shares,goal:2},{text:'홍익 마음 모으기',now:s.heart,goal:65}];default:return [{text:'잔치 식량 준비',now:s.food,goal:60},{text:'앞선 이야기 배움 마치기',now:s.learned.length,goal:5}]}}
function renderSites(){ $('#sites').innerHTML=s.lots.map((l,i)=>{let p=POS[i],b=l?TYPES.find(t=>t.id===l.id):null;return `<button data-site="${i}" class="site ${l?(l.remaining>0?'constructing':'built'):'empty'}" style="left:${p[0]}%;top:${p[1]}%;--site-x:${p[0]}%;--site-y:${p[1]}%" aria-label="${i+1}번 터 ${b?b.name:'건설하기'}">${b?`<div class="art sprite-${b.sprite}"></div><span class="building-label">${b.name}${l.remaining>0?' · 건설 중':''}</span>${l.remaining>0?`<progress max="10" value="${10-l.remaining}"></progress>`:''}`:'+'}</button>`}).join('');}
function renderStatic(){const c=STAGES[s.stage];$('#stageLabel').textContent=`제${s.stage+1}장 · ${c.title}`;$('#missionTitle').textContent='📜 임무 목록';$('#missionDescription').textContent=c.desc;$('#storyLabel').textContent=c.label;$('#storyText').textContent=c.story;$('#storyNote').textContent=c.note;$('#storyEmblem').textContent=['一','二','三','四','五'][s.stage];$('#storySteps').innerHTML=STAGES.map((_,i)=>`<span class="${i<=s.stage?'current':''}" title="제${i+1}장"></span>`).join('');$('#guardianLock').hidden=s.stage>0;$('#guardianButtons').innerHTML=s.stage>0?[['rain','☂','우사','비를 내려 가뭄 해결'],['cloud','☁','운사','먹구름을 걷어 폭우 해결'],['wind','≋','풍백','바람을 잠재워 강풍 해결']].map(([id,icon,name,desc])=>`<button class="guardian" data-skill="${id}"><span>${icon}</span><div><b>${name}</b><small>${desc}</small></div><em></em></button>`).join(''):'';$('#buildCards').innerHTML=TYPES.map(b=>`<button class="build-card" data-build="${b.id}"><div class="art sprite-${b.sprite}"></div><span><b>${b.name}</b><small>${b.desc}</small><em>${s.stage<b.stage?'제4장에 열려요':`◆-${b.wood} · 🌾-${b.food}`}</em></span></button>`).join('');renderSites();renderSpecial();render();}
function renderSpecial(){const el=$('#special');el.hidden=s.stage<2||s.finished;if(s.stage===2)el.innerHTML='<div class="mini">곰을 위한 돌봄</div><h3>쑥과 마늘 꾸러미</h3><p>식량 -15 · 목재 -5<br>한 번 보내면 20초 동안 기다려요.</p><button id="care" class="gold">꾸러미 보내기</button><p id="careStatus"></p>';else if(s.stage>=3)el.innerHTML='<div class="mini">마을의 나눔</div><h3>함께 먹는 한 끼</h3><p>식량 -20 → 홍익 +12<br>모임터가 있어야 나눌 수 있어요.</p><button id="share" class="gold">이웃과 식량 나누기</button>';}
function celebrateObjective(li){if(!li)return;li.classList.add('pop');setTimeout(()=>li.classList.remove('pop'),700);const r=li.getBoundingClientRect();if(r.width===0&&r.height===0)return;const box=li.querySelector('span')||li;const cr=box.getBoundingClientRect();const star=document.createElement('span');star.className='obj-star-embed';star.textContent='⭐';star.style.left=(cr.left+cr.width/2)+'px';star.style.top=(cr.top+cr.height/2)+'px';document.body.append(star);SFX?.star();setTimeout(()=>star.remove(),1950)}
function render(){for(const k of ['food','wood','heart'])$('#'+k).textContent=Math.floor(s[k]);$('#population').textContent=population();$('#foodRate').textContent='수확 중';$('#woodRate').textContent='벌목 중';$('#elapsed').textContent=Math.floor(s.time/60).toString().padStart(2,'0')+':'+Math.floor(s.time%60).toString().padStart(2,'0');const obj=objectives(),ready=obj.every(o=>o.now>=o.goal);if(render._prevStage!==s.stage){render._prevStage=s.stage;render._prevDone=obj.map(()=>false)}const newlyDone=obj.map((o,i)=>{const done=o.now>=o.goal;const isNew=done&&!render._prevDone[i];render._prevDone[i]=done;return isNew});$('#objectives').innerHTML=obj.map((o,i)=>`<li data-obj="${i}" class="${o.now>=o.goal?'done':''}"><span>${o.now>=o.goal?'✓':'◇'}</span><b>${o.text}<small>${Math.min(Math.floor(o.now),o.goal)} / ${o.goal}</small></b></li>`).join('');newlyDone.forEach((isNew,i)=>{if(isNew)celebrateObjective($('[data-obj="'+i+'"]'))});$('#missionProgress').style.width=obj.reduce((v,o)=>v+Math.min(o.now/o.goal,1),0)/obj.length*100+'%';$('#advance').disabled=!ready&&!s.finished;$('#advance').textContent=s.finished?'완성한 나라 돌아보기':ready?(s.stage===4?'개천절 잔치 열기 ✦':'다음 이야기로 →'):'임무를 진행해 주세요';$('#world').classList.toggle('placing',!!selected);$('#cancelBuild').hidden=!selected;$('#buildHint').textContent=selected?TYPES.find(b=>b.id===selected).name+' · 지도에서 빈 터를 선택해요':'건물을 고른 뒤 빛나는 빈 터를 눌러요';document.querySelectorAll('[data-build]').forEach(el=>{const b=TYPES.find(t=>t.id===el.dataset.build);el.classList.toggle('active',selected===b.id);el.disabled=s.finished||s.stage<b.stage||count(b.id,true)>=b.max||s.wood<b.wood||s.food<b.food;el.setAttribute('aria-pressed',selected===b.id)});$('#pause').textContent=s.paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',s.paused?'게임 계속':'일시 정지');$('#pauseBanner').hidden=!s.paused||s.finished;$('#speed').textContent=s.speed+'×';const w=s.event;$('#weatherName').textContent=w?w.name:'온화한 날씨';$('#weatherDescription').textContent=w?w.effect:'주민들이 일하기 좋은 날이에요.';$('#weatherIcon').textContent=w?w.icon:'☀';$('#weatherEvent').hidden=!w;$('#eventText').textContent=w?w.text:'';$('#weatherFx').className=w?w.class:'';document.querySelectorAll('[data-skill]').forEach(el=>{const id=el.dataset.skill;el.disabled=s.finished||s.cooldown[id]>0;el.classList.toggle('ready',!!w&&w.skill===id);el.querySelector('em').textContent=s.cooldown[id]>0?Math.ceil(s.cooldown[id])+'초':'준비'});if($('#care')){$('#care').disabled=s.care>=3||s.careTime>0||s.food<15||s.wood<5;$('#careStatus').textContent=s.careTime>0?`곰이 기다리고 있어요 · ${Math.ceil(s.careTime)}초`:`돌봄 ${s.care} / 3회 완료`;}if($('#share')){$('#share').disabled=!count('square')||s.food<20||s.shareCooldown>0;$('#share').textContent=s.shareCooldown>0?Math.ceil(s.shareCooldown)+'초 후 다시 나누기':'이웃과 식량 나누기';}}
function chooseBuild(id){const b=TYPES.find(t=>t.id===id);if(!b||s.stage<b.stage||s.finished)return false;selected=id;render();return true}
function build(i){if(!Number.isInteger(i)||i<0||i>=s.lots.length||s.finished)return false;if(s.lots[i]){const l=s.lots[i],b=TYPES.find(x=>x.id===l.id);notify(b.name+' · '+(l.remaining>0?'주민들이 짓고 있어요.':b.desc));return false}const b=TYPES.find(t=>t.id===selected);if(!b){notify('먼저 아래에서 지을 건물을 골라 주세요.');return false}if(s.stage<b.stage||count(b.id,true)>=b.max||s.food<b.food||s.wood<b.wood)return false;s.food-=b.food;s.wood-=b.wood;s.lots[i]={id:b.id,remaining:10};selected=null;notify(b.name+' 건설을 시작했어요. 10초 뒤 완성돼요.');renderSites();render();return true}
function cast(id){if(s.stage<1||s.finished||!Object.hasOwn(s.cooldown,id)||s.cooldown[id]>0)return false;if(!s.event){notify('지금은 하늘이 평온해요. 조력자들은 다음 사건을 기다려요.');return false}if(s.event.skill!==id){notify('이 사건에는 '+s.event.who+'의 힘이 필요해요. 날씨 설명을 살펴보세요.');return false}const w=s.event;if(!s.solved.includes(w.id))s.solved.push(w.id);s.event=null;s.cooldown[id]=35;s.heart=Math.min(100,s.heart+8);s.eventAt=s.time+18;notify(w.who+'의 도움으로 백성들의 삶이 다시 안정되었어요! 홍익 +8.');SFX?.weather();render();return true}
function care(){if(s.stage!==2||s.care>=3||s.careTime>0||s.food<15||s.wood<5)return false;s.food-=15;s.wood-=5;s.care++;s.careTime=20;notify('곰에게 쑥과 마늘을 전했어요. 잠시 기다리며 마을을 돌봐요.');render();return true}
function share(){if(s.stage<3||!count('square')||s.food<20||s.shareCooldown>0)return false;s.food-=20;s.shares++;s.heart=Math.min(100,s.heart+12);s.shareCooldown=12;notify('함께 먹으니 마음도 든든해요. 홍익 +12');SFX?.share();render();return true}
function update(dt){if(s.paused||s.finished||$('#modal').open||document.hidden)return;s.time+=dt;for(const k in s.cooldown)s.cooldown[k]=Math.max(0,s.cooldown[k]-dt);s.shareCooldown=Math.max(0,s.shareCooldown-dt);const wasCare=s.careTime;s.careTime=Math.max(0,s.careTime-dt);if(wasCare>0&&s.careTime===0)notify(s.care===3?'곰의 기다림이 끝났어요. 웅녀의 이야기를 만나 보세요.':'다음 돌봄을 준비할 수 있어요.');let changed=false;s.lots.forEach((l,i)=>{if(l&&l.remaining>0){l.remaining=Math.max(0,l.remaining-dt);if(l.remaining===0){changed=true;if(l.id==='square')s.heart=Math.min(100,s.heart+15);notify(TYPES.find(b=>b.id===l.id).name+' 완성!');floatText(POS[i][0],POS[i][1],'완성 ✦');SFX?.build()}}});if(changed){spawnPeople();renderSites()}s.npcs.forEach(n=>updateNPC(n,dt));document.querySelectorAll('.site progress').forEach(el=>{let i=Number(el.parentElement.dataset.site);el.value=10-s.lots[i].remaining});if(s.stage===1&&!s.event&&s.time>=s.eventAt){let next=s.solved.length%3;s.event={...WEATHER[next]};notify(s.event.name+'! '+s.event.who+'에게 도움을 청해요.')}if(s.stage>=2&&s.time>=s.communityAt){s.communityAt=s.time+110;communityEvent()}uiClock+=dt;if(uiClock>.25){uiClock=0;render()}}
function communityEvent(){show('<div class="mini">마을 사건 · 게임용 창작</div><h2>길 위에서 만난 이웃</h2><p>숲을 지나던 이웃이 잠시 쉬어 갈 곳을 찾고 있어요. 우리 마을은 어떻게 도울까요?</p><div class="answers"><button data-community="meal" '+(s.food<12?'disabled':'')+'>따뜻한 식사를 나눈다 · 식량 12 / 홍익 +10</button><button data-community="guide">주민이 안전한 길을 안내한다 · 홍익 +5</button></div><p class="subtle">선택하는 동안 마을의 시간은 멈춰 있어요.</p>')}
function enterStage(){s.stage++;s.event=null;s.eventAt=s.time+8;s.communityAt=s.time+80;if(s.stage===2){let bear=document.createElement('div');bear.className='bear art sprite-7';bear.id='bear';$('#world').append(bear)}if(s.stage===3)$('#bear')?.remove();renderStatic();notify('제'+(s.stage+1)+'장 · '+STAGES[s.stage].title+' — 새로운 미션이 열렸어요.');SFX?.advance();}
function advance(){if(s.finished){ending();return}if(!objectives().every(o=>o.now>=o.goal))return;quizQueue=[...STAGES[s.stage].lessons];quizIndex=0;quizDone=()=>{if(s.stage<4){$('#modal').close();enterStage()}else{s.food=Math.max(0,s.food-300);s.finished=true;render();ending()}};showQuiz()}
function showQuiz(){const n=quizQueue[quizIndex],l=lessons[n];show(`<div class="mini">이야기 속 배움 · ${l.type}</div><h2>${l.title}</h2><p>${l.text}</p><p><b>${l.question}</b></p><div class="answers">${l.answers.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div><p class="subtle">이야기를 읽는 동안 게임은 잠시 멈춰요.</p>`)}
function answer(i){if(!quizQueue.length)return false;let n=quizQueue[quizIndex],l=lessons[n];if(i!==l.correct){$('#feedback').innerHTML='<p class="feedback wrong">❌ 틀렸어요! 다시 생각해 보세요. 위 이야기에서 단서를 찾을 수 있어요.</p>';SFX?.wrong();return false}if(!s.learned.includes(n)){s.learned.push(n);s.heart=Math.min(100,s.heart+5)}$('.answers').innerHTML='';$('#feedback').innerHTML=`<p class="feedback correct">✅ 맞았어요! ${l.why}</p><button class="gold" id="continueQuiz">${quizIndex+1<quizQueue.length?'이어서 읽기':'마을로 돌아가기'}</button>`;SFX?.correct();render();return true}
function continueQuiz(){quizIndex++;if(quizIndex<quizQueue.length)showQuiz();else{let cb=quizDone;quizQueue=[];quizDone=null;cb?.()}}
function ending(){show(`<div class="mini">우리의 나라 · 고조선</div><h2>함께 열었기에 더 빛나는 날</h2><p>주민들이 땀 흘려 모은 자원, 자연과 어울리는 지혜, 이웃을 향한 마음으로 나라를 세웠어요.</p><div class="end-score">6 / 6 <small style="font-size:15px">배움 완료 · 홍익 ${s.heart}</small></div><p>10월 3일 개천절을 기억하며, 학교에서 실천할 나의 작은 홍익인간 약속을 적어 보세요.</p><textarea id="reflection" aria-label="나의 실천 약속" placeholder="혼자 있는 친구에게 먼저 말을 걸어요."></textarea><p class="subtle">기록은 현재 탭에서만 유지돼요. 새로고침하면 게임이 초기화돼요.</p><button id="promise" class="gold">나의 약속 남기기</button>`);$('#reflection').value=s.reflection}
function journal(){show('<div class="mini">이야기 도감 · '+s.learned.length+'/6</div><h2>신화에서 오늘까지</h2>'+lessons.map((l,i)=>`<article class="journal-entry"><h3>${s.learned.includes(i)?'✓':'◇'} ${l.title}</h3><div class="mini">${l.type}</div><p>${l.text}</p></article>`).join('')+'<article class="journal-entry"><h3>이야기와 게임을 구분해요</h3><p>신화는 공동체의 기원과 바람을 담은 이야기예요. 유적·유물과 기록을 비교하는 역사 연구와 구분해 읽어요. 주민의 작업, 건설 비용, 날씨 사건과 조력자의 해결 능력, 곰 돌봄은 학습을 위한 창작이에요.</p><p><a href="https://contents.history.go.kr/mobile/eh/view.do?code=eh_age_10&levelId=eh_n0010_0010" target="_blank" rel="noopener">국사편찬위원회 우리역사넷 · 단군 이야기</a><br><a href="https://encykorea.aks.ac.kr/Article/E0001734" target="_blank" rel="noopener">한국민족문화대백과사전 · 개천절</a></p></article>')}
function help(){show('<div class="mini">놀이 안내</div><h2>살아 움직이는 우리의 마을</h2><p><b>농부와 나무꾼</b>이 작업장으로 걸어가 일하고, 자원을 마을로 가져와요. 자원은 운반을 마칠 때 조금씩 늘어나요.</p><p>아래 건물을 고른 뒤 빈 터를 누르면 10초 동안 건설해요. 움집은 주민을, 밭과 창고는 운반량을 늘려요. 왼쪽 임무를 마치면 다음 이야기가 열려요.</p><p>제2장부터 <b>우사·운사·풍백</b>으로 날씨 사건을 해결해요. 각 능력은 사용 후 35초 동안 쉬어요. Ⅱ로 멈추고 1×로 속도를 바꿀 수 있어요.</p><p>이야기 창을 열거나 다른 탭으로 이동하면 시간은 멈춰요. 새로고침하면 처음부터 시작해요.</p><button id="reset" class="secondary">새 마을 시작하기</button>')}
function reset(){s=fresh();selected=null;$('#people').innerHTML='';$('#particles').innerHTML='';$('#bear')?.remove();close();spawnPeople();renderStatic();notify('신시의 첫날이에요. 움집과 밭을 지어 보세요.')}
$('#pause').onclick=()=>{s.paused=!s.paused;render()};$('#speed').onclick=()=>{s.speed=s.speed===1?2:1;render()};$('#soundToggle').onclick=()=>{const m=!SFX.isMuted();SFX.setMuted(m);$('#soundToggle').textContent=m?'🔇':'🔊'};$('#guide').onclick=help;$('#journal').onclick=journal;$('.close').onclick=close;$('#modal').addEventListener('cancel',e=>{e.preventDefault();close()});$('#advance').onclick=advance;$('#cancelBuild').onclick=()=>{selected=null;render()};$('#readStory').onclick=()=>{let c=STAGES[s.stage];show(`<div class="mini">제${s.stage+1}장 · ${c.label}</div><h2>${c.title}</h2><p>${c.story}</p><p class="feedback">${c.note}</p>`)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;SFX?.click();if(b.dataset.build)chooseBuild(b.dataset.build);if(b.dataset.site!==undefined)build(Number(b.dataset.site));if(b.dataset.skill)cast(b.dataset.skill);if(b.id==='care')care();if(b.id==='share')share();if(b.dataset.answer!==undefined)answer(Number(b.dataset.answer));if(b.id==='continueQuiz')continueQuiz();if(b.dataset.community){if(b.dataset.community==='meal'){if(s.food<12)return;s.food-=12;s.heart=Math.min(100,s.heart+10)}else s.heart=Math.min(100,s.heart+5);close();render();notify('이웃이 고마운 마음을 전했어요.')}if(b.id==='promise'){s.reflection=$('#reflection').value.trim();if(!s.reflection){$('#reflection').focus();return}close();notify('나의 약속: '+s.reflection)}if(b.id==='reset')show('<h2>새 마을을 시작할까요?</h2><p>현재의 건물과 배움 기록이 초기화돼요.</p><button id="confirmReset" class="gold">처음부터 시작</button>');if(b.id==='confirmReset')reset()});
function frame(t){let dt=last?Math.min((t-last)/1000,.15):0;last=t;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#toast').classList.add('quiet')}update(dt*s.speed);requestAnimationFrame(frame)}
reset();requestAnimationFrame(frame);
