/* Settlement growth, expanded missions and weather announcements. */
const stageGoals=['건물을 지어 마을의 주민을 늘리세요','날씨를 다스려 풍요롭게 농사를 지으세요','이웃 부족들과 힘을 합치세요','나라의 기틀을 다지고 홍익인간을 실천하세요','개천절을 기억하며 마지막 잔치를 준비하세요'];
const mapFiles=['village.jpg','map-stage2.jpg','map-stage3.jpg','map-stage4.jpg','map-stage4.jpg'];
const buildTargets=[{home:2,farm:2},{home:3,farm:4},{home:4,farm:5},{home:6,farm:6,store:2,square:2},{home:6,farm:6,store:2,square:2}];
const baseCosts={home:[10,32,3,11],farm:[30,10,11,3],store:[36,40,10,10],square:[32,38,10,10]};
function refreshCosts(){const stageMult=1+s.stage*0.9;for(const b of TYPES){const [wood,food,woodInc,foodInc]=baseCosts[b.id];const n=count(b.id,true);b.wood=Math.round((wood+n*woodInc)*stageMult);b.food=Math.round((food+n*foodInc)*stageMult);}}
const expandedPositions=structuredClone(POS);
layoutMap=function(){POS.splice(0,POS.length,...structuredClone(expandedPositions));renderSites();};
const growthFresh=fresh;fresh=()=>({...growthFresh(),lots:Array(26).fill(null),stageHarvest:0});
const prosperity=document.createElement('div');prosperity.id='prosperityBuildings';prosperity.innerHTML=[[58,30,2],[69,27,2],[80,35,2],[34,28,3]].map(([x,y,n])=>`<span class="art sprite-${n}" style="left:${x}%;top:${y}%"></span>`).join('');$('#world').append(prosperity);const badge=document.createElement('div');badge.id='settlementName';badge.innerHTML='<b></b>';$('#world').append(badge);
const resourceIcon=(kind)=>kind==='wood'?'<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M9 13 28 6l8 21-20 8Z" fill="#b9763b" stroke="#573d25" stroke-width="2"/><path d="m12 14 17-5M14 20l17-5M16 26l16-5" stroke="#e5b16f" stroke-width="2"/><ellipse cx="12" cy="24" rx="9" ry="12" transform="rotate(-20 12 24)" fill="#efd09a" stroke="#714b2c" stroke-width="2"/><ellipse cx="12" cy="24" rx="4" ry="7" transform="rotate(-20 12 24)" fill="none" stroke="#9b6934" stroke-width="2"/></svg>':'<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M20 23C4 14 12 2 20 10c8-8 16 4 0 13Z" fill="#f28c78" stroke="#843f3d" stroke-width="1.5"/><path d="m3 20 7 6 10 4 10-4 7-6v10l-9 7H12l-9-7Z" fill="#f2cf95" stroke="#785b36" stroke-width="1.5"/><path d="m10 26 10 4 10-4" fill="none" stroke="#bd8850" stroke-width="2"/></svg>';
for(const kind of ['wood','heart']){const box=$('#'+kind).closest('.resources>div');if(box){for(const n of [...box.childNodes])if(n.nodeType===3)n.remove();const icon=document.createElement('span');icon.className='resource-art';icon.innerHTML=resourceIcon(kind);box.prepend(icon);}}
const compactWeather=document.createElement('button');compactWeather.id='compactWeather';compactWeather.setAttribute('aria-label','현재 날씨');$('.game-controls').before(compactWeather);
const MYTH_SLIDES=[
 {img:'myth1.jpg',title:'환웅의 뜻',
  junior:'아주 먼 옛날, 하늘나라에 살던 환웅은 땅으로 내려와 사람들을 돕고 싶었어요.\n아버지 환인은 그 뜻을 알고 환웅을 보내 주었지요.',
  senior:'아주 먼 옛날, 하늘나라에 살던 환웅은 땅으로 내려와 사람들을 돕고 싶었어요.\n아버지 환인은 그 뜻을 알고 환웅을 보내 주었지요.'},
 {img:'myth2.jpg',title:'신시의 건국',
  junior:'환웅은 비와 구름, 바람을 다스리는 우사, 운사, 풍백과 함께 신단수 아래로 내려왔어요.\n그리고 사람들이 농사를 짓고 서로 도우며 살도록 이끌었답니다.',
  senior:'환웅은 비와 구름, 바람을 다스리는 우사, 운사, 풍백과 함께 신단수 아래로 내려왔어요.\n그리고 사람들이 농사를 짓고 서로 도우며 살도록 이끌었답니다.'},
 {img:'myth3.jpg',title:'곰과 호랑이의 시험',
  junior:'어느 날, 곰과 호랑이가 찾아와 사람이 되고 싶다고 했어요. 환웅은 쑥과 마늘을 주며 말했지요.\n"이것을 먹으며 백 일 동안 햇빛을 보지 않으면 사람이 될 수 있단다."',
  senior:'어느 날, 곰과 호랑이가 찾아와 사람이 되고 싶다고 했어요. 환웅은 쑥과 마늘을 주며 말했지요.\n"이것을 먹으며 백 일 동안 햇빛을 보지 않으면 사람이 될 수 있단다."'},
 {img:'myth4.jpg',title:'웅녀와 단군',
  junior:'호랑이는 참지 못하고 동굴을 나갔지만, 곰은 끝까지 견뎠어요.\n그러자 스물하루 만에 여인이 되었고, \'웅녀\'라는 이름을 얻었지요.\n뒤에 환웅과 웅녀 사이에서 단군왕검이 태어났어요.',
  senior:'호랑이는 참지 못하고 동굴을 나갔지만, 곰은 끝까지 견뎠어요.\n그러자 스물하루 만에 여인이 되었고, \'웅녀\'라는 이름을 얻었지요.\n뒤에 환웅과 웅녀 사이에서 단군왕검이 태어났어요.'},
 {img:'myth5.jpg',title:'이야기 속으로',
  junior:'단군왕검은 자라서 고조선을 세우고, 널리 사람을 이롭게 한다는\n\'홍익인간\'의 뜻으로 나라를 다스렸다고 전해진답니다.',
  senior:'단군왕검은 자라서 고조선을 세우고, 널리 사람을 이롭게 한다는\n\'홍익인간\'의 뜻으로 나라를 다스렸다고 전해진답니다.'}
];
const mythIntro=document.createElement('div');mythIntro.id='mythIntro';mythIntro.hidden=true;mythIntro.innerHTML='<div class="myth-card"><p class="myth-kicker">開天 · 하늘이 열리다</p><h2 class="myth-title">단군 신화</h2><div class="myth-frame"><img id="mythSlideImg" alt=""><div class="myth-caption"><p class="myth-story" id="mythStoryText"></p><button id="mythIntroGo" class="myth-next" hidden>다음 →</button></div></div><div class="myth-dots" id="mythDots"></div></div>';document.body.append(mythIntro);
let mythSlideIndex=0;
function renderMythSlide(){const slide=MYTH_SLIDES[mythSlideIndex];const isLast=mythSlideIndex===MYTH_SLIDES.length-1;$('#mythSlideImg').src=slide.img;$('#mythDots').innerHTML=MYTH_SLIDES.map((_,i)=>`<span class="${i===mythSlideIndex?'current':i<mythSlideIndex?'seen':''}"></span>`).join('');const btn=$('#mythIntroGo');btn.hidden=true;btn.textContent=isLast?'신화 속 이야기를 따라 고조선을 만들어 볼까요?':'다음 →';btn.classList.toggle('myth-final-btn',isLast);$('.myth-caption')?.classList.toggle('final',isLast);typewriterReveal($('#mythStoryText'),slide[s.grade]||slide.senior,()=>{const b=$('#mythIntroGo');if(b)b.hidden=false;});}
function showMythIntro(){mythSlideIndex=0;mythIntro.hidden=false;mythIntro.classList.remove('flash');void mythIntro.offsetWidth;mythIntro.classList.add('flash');renderMythSlide();}
function advanceMyth(){if(mythSlideIndex<MYTH_SLIDES.length-1){mythSlideIndex++;renderMythSlide();}else{closeMythIntro();}}
function closeMythIntro(){mythIntro.hidden=true;mythIntro.classList.remove('flash');$('#game').inert=false;arrow.hidden=true;}
document.addEventListener('click',e=>{if(e.target.closest('button')?.id==='mythIntroGo')advanceMyth();});
let shownWeather=null,paintedMap=-1;
function updateMap(){if(paintedMap!==s.stage){paintedMap=s.stage;$('#terrain').style.backgroundImage=`url('${mapFiles[s.stage]}')`;$('#world').dataset.era=String(s.stage);$('#terrain').classList.remove('map-arrive');void $('#terrain').offsetWidth;$('#terrain').classList.add('map-arrive');}$('#settlementName b').textContent=stageGoals[s.stage];}
const growthConfigure=configureGrade;configureGrade=function(grade){growthConfigure(grade);const easy=grade==='junior';STAGES[0].desc=easy?'움집 2채와 밭 2곳을 만들어요. 식량 100을 수확해요.':'움집 2채와 밭 2곳을 완성하고, 주민들이 식량 100을 수확하도록 마을을 돌봐요.';STAGES[1].desc=easy?'움집 3채, 밭 4곳으로 늘려요. 세 날씨 사건도 해결해요.':'움집 3채와 밭 4곳으로 마을을 넓히고, 세 조력자와 서로 다른 날씨 사건을 해결해요.';STAGES[2].desc=easy?'움집 4채와 밭 5곳을 마련해요. 두 부족과 함께 살 길을 찾아요.':'새 이웃을 위해 움집 4채와 밭 5곳을 마련하고 두 부족과 공동체 약속을 맺어요.';STAGES[3].title=easy?'고조선을 세웠어요':'고조선, 나라로 자라나다';STAGES[3].desc=easy?'움집 6채, 밭 6곳, 창고와 모임터 2곳씩! 음식을 네 번 나눠요.':'나라의 기반을 완성해요. 움집 6채·밭 6곳·창고 2곳·모임터 2곳을 갖추고 네 번의 나눔을 실천해요.';STAGES[3].story=easy?'환웅과 웅녀 사이에서 단군왕검이 태어나 자라 나라를 세웠다. 여러 마을이 힘을 모아 큰 나라가 되었으니, 이를 고조선이라 하였다.':'신화에서는 환웅과 웅녀 사이에서 태어난 단군왕검이 조선을 세웠다고 전해진다. 여러 마을이 모여 하나의 나라로 자라나니, 이 나라를 고조선이라 이른다.';STAGES[4].desc=easy?'이 단계에서 식량 200을 새로 수확해요. 잔치 식량 300도 준비해요.':'새 단계에서 식량 200을 수확하고, 잔치를 위한 식량 300을 모아 개천절의 의미를 돌아봐요.';STAGES[4].note+=' 잔치와 도시 모습은 게임을 위한 상상이에요.';};
const growthObjectives=objectives;objectives=function(){const goals=buildTargets[s.stage];const buildingGoals=Object.entries(goals).map(([id,goal])=>({text:TYPES.find(t=>t.id===id).name+' '+goal+(id==='home'?'채':'곳')+' 완성',now:count(id),goal}));if(s.stage===0)return [...buildingGoals,{text:'주민들의 식량 수확',now:s.collected,goal:100}];if(s.stage===1)return [...buildingGoals,{text:'세 조력자로 날씨 해결',now:s.solved.length,goal:3}];if(s.stage===2)return [...buildingGoals,...growthObjectives()];if(s.stage===3)return [...buildingGoals,{text:'이웃과 식량 나누기',now:s.shares,goal:4},{text:'홍익 마음 모으기',now:s.heart,goal:85}];return [{text:'이 단계에서 새로 수확하기',now:s.collected-s.stageHarvest,goal:200},{text:'잔치 식량 준비',now:s.food,goal:300}];};
const growthNextAction=nextAction;nextAction=function(){if(!s.started||s.finished)return null;if(s.paused)return ['#pause','▶ 눌러서 계속해요'];if(s.event)return ['[data-skill="'+s.event.skill+'"]',s.event.who+'에게 도움을 청해요'];if(selected)return ['[data-site="'+s.lots.findIndex(l=>!l)+'"]','이 빈 터를 눌러요'];if(objectives().every(o=>o.now>=o.goal))return ['#advance','다음 이야기를 열어요'];const goals=buildTargets[s.stage];const wanted=Object.keys(goals).find(id=>count(id,true)<goals[id]);if(wanted){const b=TYPES.find(t=>t.id===wanted);if(s.wood>=b.wood&&s.food>=b.food)return ['[data-build="'+wanted+'"]',b.name+'을 더 지어요'];if(s.grade==='junior'){if(s.wood<b.wood)return ['#wood','목재를 모으는 중이에요'];if(s.food<b.food)return ['#food','식량을 모으는 중이에요'];}}if(s.lots.some(l=>l?.remaining>0))return ['.site.constructing','건물이 완성되기를 기다려요'];if(s.stage===3&&s.shares<4)return s.food<20?['#food','나눌 식량 20개를 모아요']:['#share',s.shareCooldown>0?'다음 나눔을 준비해요':'이웃과 식량을 나눠요'];return growthNextAction();};
const VILLAGE_EVENTS=[
 {id:'traveler',title:'길 위에서 만난 이웃',body:'숲을 지나던 이웃이 잠시 쉬어 갈 곳을 찾고 있어요. 우리 마을은 어떻게 도울까요?',choices:[{id:'meal',label:'따뜻한 식사를 나눈다',cost:{food:12},gain:{heart:10}},{id:'guide',label:'주민이 안전한 길을 안내한다',cost:{},gain:{heart:5}}]},
 {id:'harvestBoon',title:'풍년의 징조',body:'따스한 햇살 덕분에 올해 곡식이 유난히 잘 여물었어요.',auto:{gain:{food:22}}},
 {id:'timberFind',title:'숲에서 찾은 재목',body:'벌목하던 주민이 우연히 튼튼한 나무 더미를 발견했어요.',auto:{gain:{wood:16}}},
 {id:'pests',title:'곳간을 노린 들쥐',body:'들쥐 떼가 곳간에 몰래 들어와 곡식을 축냈어요.',auto:{cost:{food:10}}},
 {id:'brokenTool',title:'부러진 농기구',body:'농사 도구가 갑자기 부러져 수리가 필요해요.',auto:{cost:{wood:9}}},
 {id:'trade',title:'이웃 마을과의 교류',body:'이웃 마을에서 물건을 바꾸자고 제안해 왔어요.',choices:[{id:'foodForWood',label:'식량을 목재로 바꾼다',cost:{food:15},gain:{wood:18}},{id:'woodForFood',label:'목재를 식량으로 바꾼다',cost:{wood:15},gain:{food:18}}]},
];
let lastVillageEvent=null;
function fmtDelta(kind,amount){const sign=amount>=0?'+':'-';const label=kind==='food'?'식량':kind==='wood'?'목재':'홍익';return `${label} ${sign}${Math.abs(amount)}`;}
function describeCostGain(cost,gain){const parts=[];if(cost)for(const k in cost)parts.push(fmtDelta(k,-cost[k]));if(gain)for(const k in gain)parts.push(fmtDelta(k,gain[k]));return parts.join(' · ')||'변화 없음';}
function applyEventDelta(cost,gain){if(cost)for(const k in cost)s[k]=Math.max(0,s[k]-cost[k]);if(gain)for(const k in gain)s[k]=k==='heart'?Math.min(100,s[k]+gain[k]):s[k]+gain[k];}
function villageEvent(){if(s.stage<1||s.finished||$('#modal').open)return;const pool=VILLAGE_EVENTS.filter(e=>e.id!==lastVillageEvent);const ev=pool[Math.floor(Math.random()*pool.length)];lastVillageEvent=ev.id;
 if(ev.auto){show(`<div class="mini">마을 사건 · 게임용 창작</div><h2>${ev.title}</h2><p>${ev.body}</p><p class="feedback">${describeCostGain(ev.auto.cost,ev.auto.gain)}</p><button id="villageEventOk" class="gold" data-village-event="${ev.id}">확인</button>`);}
 else{show(`<div class="mini">마을 사건 · 게임용 창작</div><h2>${ev.title}</h2><p>${ev.body}</p><div class="answers">${ev.choices.map(c=>{const insufficient=c.cost&&Object.entries(c.cost).some(([k,v])=>s[k]<v);return `<button data-village-choice="${c.id}" data-village-event="${ev.id}" ${insufficient?'disabled':''}>${c.label} · ${describeCostGain(c.cost,c.gain)}</button>`}).join('')}</div><p class="subtle">선택하는 동안 마을의 시간은 멈춰 있어요.</p>`);}
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.id==='villageEventOk'){const ev=VILLAGE_EVENTS.find(x=>x.id===b.dataset.villageEvent);if(ev&&ev.auto)applyEventDelta(ev.auto.cost,ev.auto.gain);close();render();notify(ev?ev.title+' — 마을에 작은 변화가 생겼어요.':'');}
 if(b.dataset.villageChoice){const ev=VILLAGE_EVENTS.find(x=>x.id===b.dataset.villageEvent);const choice=ev?.choices.find(c=>c.id===b.dataset.villageChoice);if(choice)applyEventDelta(choice.cost,choice.gain);close();render();notify('선택에 따라 마을에 변화가 생겼어요.');}
});
function showWeatherAlert(){const w=s.event;if(!w||$('#modal').open)return;shownWeather=w;$('#modal').classList.add('weather-alert');show(`<div class="mini">사건이 일어났어요!</div><div class="alert-weather-icon">${w.icon}</div><h2>${w.name}</h2><p class="weather-impact">${w.effect}</p><p>${w.text}</p><p class="question-cue">누구에게 도움을 청할까요?</p><div class="weather-choices">${[['rain','☂','우사','비를 다스려요'],['cloud','☁','운사','구름을 다스려요'],['wind','≋','풍백','바람을 다스려요']].map(([id,icon,name,desc])=>`<button data-skill="${id}" ${s.cooldown[id]>0?'disabled':''}><span>${icon}</span><b>${name}</b><small>${s.cooldown[id]>0?'잠시 쉬는 중':desc}</small><em hidden></em></button>`).join('')}</div><p id="weatherAnswer" role="status" aria-live="polite"></p><button class="secondary" id="laterWeather">마을에서 대응하기</button><p class="subtle">날씨 대응은 게임용 창작이에요. 읽는 동안 시간은 멈춰요.</p>`);}
const growthStartGrade=startGrade;startGrade=function(grade){const ok=growthStartGrade(grade);if(ok){$('#game').inert=true;showMythIntro();}return ok;};
function typewriterReveal(el,text,onDone,charDelay){if(!el)return;if(el._typeTimers){el._typeTimers.forEach(clearTimeout);el._typeTimers=null}const chars=[...text];el.innerHTML=chars.map(c=>c==='\n'?'<br>':c===' '?' ':`<span class="flow-char">${c}</span>`).join('');const spans=el.querySelectorAll('.flow-char');const delay=charDelay||Math.max(22,Math.min(48,4600/Math.max(chars.length,1)));const timers=[];spans.forEach((sp,i)=>{timers.push(setTimeout(()=>sp.classList.add('show'),i*delay))});timers.push(setTimeout(()=>{onDone&&onDone()},spans.length*delay+420));el._typeTimers=timers;}
function showStageIntro(){const c=STAGES[s.stage];$('#modal').classList.add('stage-intro');show(`<div class="mini">제${s.stage+1}장 · ${c.label}</div><h2>${c.title}</h2><p id="stageStoryText" class="typewriter-text"></p><button id="stageIntroGo" class="gold" hidden>이야기 계속하기</button>`);typewriterReveal($('#stageStoryText'),c.story,()=>{const btn=$('#stageIntroGo');if(btn)btn.hidden=false;});}
document.addEventListener('click',e=>{if(e.target.closest('button')?.id==='stageIntroGo')close();});
const growthClose=close;close=function(){growthClose();$('#modal').classList.remove('weather-alert');$('#modal').classList.remove('stage-intro');};$('.close').onclick=close;
const growthCast=cast;cast=function(id){const result=growthCast(id);if(result){s.eventAt=s.time+(s.stage===1?25:65);if($('#modal').classList.contains('weather-alert'))close();compactWeather.classList.remove('danger');}else if($('#modal').classList.contains('weather-alert')&&s.event){$('#weatherAnswer').textContent='이 날씨에는 '+s.event.who+'의 도움이 필요해요. 다시 골라 보세요.';}return result;};
document.addEventListener('click',e=>{if(e.target.closest('button')?.id==='laterWeather')close();});
const growthRender=render;render=function(){refreshCosts();growthRender();updateMap();compactWeather.classList.toggle('danger',!!s.event);compactWeather.textContent=s.event?s.event.icon+' '+s.event.name:'☀ 온화함';compactWeather.setAttribute('aria-label',s.event?s.event.name:'현재 날씨: 온화함');const wb=$('#weatherBig');if(wb){wb.hidden=!s.event;if(s.event){$('#wbIcon').textContent=s.event.icon;$('#wbName').textContent=s.event.name;$('#wbEffect').textContent=s.event.effect;$('#wbText').textContent=s.event.text;}}document.querySelectorAll('[data-build]').forEach(el=>{const b=TYPES.find(t=>t.id===el.dataset.build);const cost=el.querySelector('em');if(cost)cost.textContent=s.stage<b.stage?'제4장에 열려요':`목재-${b.wood} · 식량-${b.food}`;});};
const growthEnter=enterStage;enterStage=function(){growthEnter();s.stageHarvest=s.collected;shownWeather=null;updateMap();if(s.stage===3)notify('고조선이 세워졌어요! 마을들이 모인 나라의 터전을 더 튼튼하게 가꿔요.');showStageIntro();};
const growthUpdate=update;update=function(dt){growthUpdate(dt);if(s.paused||s.finished||$('#modal').open||document.hidden)return;if(s.event){s.food=Math.max(0,s.food-dt*1.4);s.wood=Math.max(0,s.wood-dt*0.9);}};
const growthReset=reset;reset=function(){paintedMap=-1;shownWeather=null;growthReset();$('#modal').classList.remove('weather-alert');layoutMap();refreshCosts();renderStatic();};
const growthHelp=help;help=function(){growthHelp();$('#modalBody').insertAdjacentHTML('beforeend','<p class="subtle">건물을 더 지을수록, 그리고 이야기가 진행될수록 건설에 필요한 자원이 크게 늘어요. 지은 건물은 다음 단계에도 남아요. 단계마다 배경이 발전하고, 제4장에서 고조선의 모습이 펼쳐져요. 지도의 주변 건물은 배경이며 건설 개수에는 포함되지 않아요.</p>');};$('#guide').onclick=help;
communityEvent=villageEvent;

/* 가끔 지나다니는 주민들 — 자원 채집과 무관하게 가끔씩 오가는 배경 인물 */
const EXTRA_VARIANTS=3;
const extraFresh=fresh;fresh=()=>({...extraFresh(),extras:[],extraTimer:5+Math.random()*5,extraSeq:0});
function extraMax(stage){return stage<=0?0:stage<3?1:2}
function extraInterval(stage){const base=[30,24,19,15,12][Math.min(stage,4)];return base+Math.random()*9}
function extraEdge(){const west=Math.random()<.5;const y=28+Math.random()*44;return {x:west?-7:107,y}}
function spawnExtra(){if(s.extras.length>=extraMax(s.stage))return;const start=extraEdge();const mid={x:18+Math.random()*60,y:30+Math.random()*40};const end=extraEdge();const id='ex'+(s.extraSeq++);const n={id,variant:Math.floor(Math.random()*EXTRA_VARIANTS),x:start.x,y:start.y,midX:mid.x,midY:mid.y,endX:end.x,endY:end.y,phase:'in',pauseLeft:2.5+Math.random()*4,stepped:false};s.extras.push(n);const el=document.createElement('div');el.className='npc extra-wanderer';el.id=n.id;el.innerHTML=`<div class="art extra-${n.variant}"></div>`;$('#people').append(el)}
function updateExtras(dt){s.extraTimer=(s.extraTimer??6)-dt;if(s.extraTimer<=0){spawnExtra();s.extraTimer=extraInterval(s.stage)}for(let i=s.extras.length-1;i>=0;i--){const n=s.extras[i];let moved=false;if(n.phase==='in'||n.phase==='out'){const tx=n.phase==='in'?n.midX:n.endX,ty=n.phase==='in'?n.midY:n.endY;const dx=tx-n.x,dy=ty-n.y,dist=Math.hypot(dx,dy);const step=dt*3.4;if(dist<=step){n.x=tx;n.y=ty;n.phase=n.phase==='in'?'pause':'gone'}else{n.x+=dx/dist*step;n.y+=dy/dist*step;moved=true}}else if(n.phase==='pause'){n.pauseLeft-=dt;if(n.pauseLeft<=0)n.phase='out'}n.stepped=moved;const el=document.getElementById(n.id);if(n.phase==='gone'){el?.remove();s.extras.splice(i,1);continue}if(el){el.style.left=n.x+'%';el.style.top=n.y+'%';el.className='npc extra-wanderer '+(moved?'walking step':'walking')}}}
const extraUpdate=update;update=function(dt){extraUpdate(dt);if(s.paused||s.finished||$('#modal').open||document.hidden)return;updateExtras(dt)};

layoutMap();reset();
